config/routes.rb
Rails.application.routes.draw do


  mount ForestLiana::Engine => '/forest'
  	devise_for :users, :controllers => {
  		:omniauth_callbacks => 'users/omniauth_callbacks'
  	}


	resources :products, only: [:index] do
	  resources :orders, only: :create
	end

	resources :orders, only: [:index, :destroy] do
		collection do
			delete 'empty_cart'
		end
	end		

	resources :billings, only: [] do
		collection do
 			get 'pre_pay'
 			get 'execute'
 		end
	end

	root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
	 has_many :orders
 	 has_many :users, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

	has_many :orders
 	has_many :products, through: :orders  
 	has_many :billings 

 	def self.from_omniauth(auth)
 		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
 			user.email = auth.info.email
 			user.password = Devise.friendly_token[0,20]
 			user.name = auth.info.name
 		end
 	end	

 	def cart
 		orders.where(payed: false)      	
 	end      

 	def has_any_order?
 		orders.where(payed: false).count > 0
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

    	def pre_pay
    	#Consultar carro de compra.
        orders = current_user.cart

        #Cálculo del total.
        @total = orders.pluck("price * quantity").sum()

        #Generando array de hashes con los productos.
        @items = orders.map do |order|
          item = {}
          item[:name] = order.product.name
          item[:sku] = order.id.to_s
          item[:price] = order.price.to_s
          item[:currency] = 'USD'
          item[:quantity] = order.quantity
          item
        end

        @payment = PayPal::SDK::REST::Payment.new(
          {
            :intent =>  "sale",
            :payer =>  {
              :payment_method =>  "paypal" },
            :redirect_urls => {
              :return_url => "http://localhost:3000/billings/execute",
              :cancel_url => "http://localhost:3000/" },
            :transactions =>  [{
              :item_list => {
                :items => @items},
              :amount =>  {
                :total =>  @total.to_s,
                :currency =>  "USD" },
              :description =>  "This is the payment transaction description." }]}
        )

        if @payment.create
          #Redirige a PayPal
    	redirect_url = @payment.links.find{|v| v.method == "REDIRECT" }.href
    	redirect_to redirect_url
        else
          @payment.error
        end
      end #Cierra pre_pay

      def execute
        @paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])

        if @paypal_payment.execute(payer_id: params[:PayerID])

          amount = @paypal_payment.transactions.first.amount.total

             billing = Billing.create(
             user: current_user,
             code: @paypal_payment.id,
             payment_method: 'paypal',
             amount: amount,
             currency: 'USD'
             )

             orders = current_user.cart
             orders.update_all(payed: true, billing_id: billing.id)

             redirect_to root_path, notice: "La compra se realizó con éxito!"          
        else
          render plain: "No se puedo generar el cobro en PayPal."
        end
      end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_cart, only: [:empty_cart, :index]

	def empty_cart
		@cart.destroy_all
		redirect_to orders_path, notice: 'Se ha vaciado el carro'

	end

	def index
		@orders = @cart

		@total = @orders.inject(0) {|total, order|total += order.product.price}

		@subtotal = @orders.inject(0) {|subtotal, order|subtotal += order.product.price * order.quantity}
	end

	def destroy
		@order = Order.find(params[:id])

		if @order.quantity == 1
			@order.destroy
			redirect_to orders_path, notice: 'El producto ha sido removido del carro'

		elsif @order.quantity > 1
			new_quantity = @order.quantity - 1
			@order.update(quantity: new_quantity)
			redirect_to orders_path, notice: 'Carro Actualizado'
			end		
		
	end

	def create
		@previous_order = Order.find_by(user_id: current_user.id, product_id: params[:product_id], payed: false)

		if @previous_order.present?
			new_quantity = @previous_order.quantity + 1
			@previous_order.update(quantity: new_quantity)
			redirect_to root_path, notice: 'La orden se ha generado con exito'
		else
			@order = Order.new()
			@product = Product.find(params[:product_id])
			@order.product = @product
			@order.price = @product.price
			@order.user = current_user

		if @order.save
			redirect_to root_path, notice: 'El producto ha sido agregado al carro'
		else
			redirect_to root_path, alert: 'El producto no ha sido agregado al carro'	
		end
	end
  end	

  	private

  	def set_cart
  		@cart = current_user.cart
  		
  	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
	  	if params[:buscar].present?
	  		consulta = params[:buscar].capitalize
	  		@products = Product.where('name like?', "%#{consulta}%")

	  	else
	  	 	@products = Product.all
	  	end
 	end
end 

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
			sign_in_and_redirect @user
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			redirect_to root_path, notice: 'Error al iniciar sesión con Facebook.'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarroDeCompra</title>
    <%= csrf_meta_tags %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>

      <% if notice.present?  %>
          <div class="alert alert-success" role="alert"> 
              <%= notice %>
          </div>     
        <% end %>


      <% if alert.present?  %>
          <div class="alert alert-danger" role="alert"> 
              <%= alert %>
          </div>     
        <% end %>

    <%= yield %>





 
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/index.html.erb
<br>
<div class="row">
	<div class="col-md-2">
		 <%= link_to 'Continuar Comprando', root_path, class: 'btn btn-dark' %>
	</div>
	<div class="col-md-2 offset-md-8">
		<%= link_to 'Vaciar Carro', empty_cart_orders_path, class: 'btn btn-danger', method: :delete %>
	</div>
</div>

<br><br>

<% if current_user.has_any_order?%>
	<table class="table table-hover">
	<tr>
		<th>Producto</th>
		<th>Valor Unitario</th>
		<th>Cantidad</th>
		<th>SubTotal</th>
		<th>Remover</th>
	</tr>
<% @orders.each do |order| %>
		<tr>
			<td>
			<%= order.product.name %>
			</td>
			<td>
			$<%= order.price %>
		  </td>	
		  <td>
		  	<%= order.quantity %>
		  </td>
		  <td>
		  	$<%= order.quantity * order.product.price %>
		  </td>
		  <td>
		  	<%= link_to order_path(order), class: 'btn btn-danger btn-sm', method: :delete do %> <i class="fas fa-trash"></i>
		  	 <% end %>
		  </td>
		</tr>	
	<% end  %>

  <tr>
	<th>Total:</th>
	<th>
		<%= @total %>
	</th>
	<th></th>

	<th>
		<%= @subtotal %>
	</th>

  </tr>
</table>
<div class="row">
	<div class="col-md-2 offset-md-9">
		<%= link_to 'Confirmar compra', pre_pay_billings_path, class: 'btn btn-success' %>
	</div>
</div>
	<% else %>
		<h5>No tienes productos en el Carro.</h5>
<% end %>

app/views/products/_product.html.erb
 <% @products.each do |product| %>
   <div class="col-md-3">
     <div class="card text-center" style="margin-top: 30px;">
       <%= image_tag product.photo, class: 'card-img-top' %>
       <div class="card-body">
         <h6 class="card-title"><%= product.name %></h6>
         <p class="card-text">$<%= product.price %></p>

         <%= link_to product_orders_path(product), class: "btn btn-success", method: :post do %>
           <i class="fas fa-cart-plus"></i>
         <% end %>

       </div>
     </div>
   </div>
 <% end %>

app/views/products/index.html.erb
<br>
<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">
          <i class="fas fa-search"></i>
        </span>
      </div>
      <input type="text" class="form-control" placeholder="Busca un producto aquí..." id="buscar">
    </div>
  </div>
</div>


<div class="row" id="products">
  <%= render @products %>
</div>

<script type="text/javascript">
  $('#buscar').keyup(function(){

    $.ajax({
      url: '<%= products_path %>',
      type: 'GET',
      dataType: 'script',
      data: {buscar: $('#buscar').val()},
    })
    .done(function() {
      console.log("success");
    })
    .fail(function() {
      console.log("error");
    })
    
});
</script>

app/views/products/index.js.erb
$('#products').html("<%= j render @products  %>")

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <div class="container">
   <a class="navbar-brand" href="<%= root_path %>">Mi App</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNav">
     <ul class="navbar-nav">
       <li class="nav-item">
         <%= link_to "Mi Carro", orders_path, class: "nav-link" %>
       </li>
     </ul>
     <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
         <li class="nav-item">
           <%= link_to current_user.email, "#", class: 'nav-link' %>
         </li>
         <li class="nav-item">
           <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
         </li>
       <% else %>
         <li class="nav-item">
           <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
         </li>
         <li class="nav-item">
           <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
         </li>
       <% end %>
     </ul>
   </div>
 </div>
</nav>